### ISSUE TITLE
Support user token verification

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM.NET.SDK#7]
XUMM SDK 1.1.2 adds support for the new user token verification endpoint:
- Endpoint: https://xumm.readme.io/reference/user-tokens
- Commit: https://github.com/XRPL-Labs/XUMM-SDK/commit/33c43311226d9f42aabac1b5cc09ac2e04cc421c

This change features two methods on the parent SDK object, `verifyUserTokens` (to verify an array of tokens) and `verifyUserToken` (to verify a single user token).

Sample code in TypeScript:
```
    console.log(await Sdk.verifyUserTokens([
      '691d5ae8-968b-44c8-8835-f25da1214f35',
      'b12b59a8-83c8-4bc0-8acb-1d1d743871f1',
      '51313be2-5887-4ae8-9fda-765775a59e51',
      'testing an invalid record'
    ]))
```
» Returns an **array** with User Token Validity records: https://github.com/XRPL-Labs/XUMM-SDK/blob/33c43311226d9f42aabac1b5cc09ac2e04cc421c/deno/types/Meta/UserTokens.ts#L1

Or single User Token calls:

```
    console.log('a', await Sdk.verifyUserToken('691d5ae8-968b-44c8-8835-f25da1214f35'))
    console.log('b', await Sdk.verifyUserToken('691d5ae8-968b-44c8-8835-f25da1214f36'))
    console.log('c', await Sdk.verifyUserToken('testing an invalid record'))
```
» Each call returns either a single User Token Validity record, or null.

**Comment by DominiqueBlomsma** [comment]
Support for User Token validation has been added in release [v1.2.0](https://github.com/XRPL-Labs/XUMM.NET.SDK/releases/tag/v1.2.0).
